name: Push strings to Lokalise

on:
  push:
    branches: [dev]
    paths:
      - 'composeApp/src/commonMain/composeResources/values/strings.xml'

jobs:
  push-strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to Lokalise
        uses: lokalise/push-action@v1
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: ${{ secrets.LOKALISE_PROJECT_ID }}
          file: composeApp/src/commonMain/composeResources/values/strings.xml
          lang_iso: en
          replace_modified: true
          cleanup_mode: true
